hastane1/hastane1/Controllers/AsistanController.cs
using Microsoft.AspNetCore.Mvc;
using hastane1.Models;
using Microsoft.AspNetCore.Http.HttpResults;


namespace hastane1.Controllers
{
	public class AsistanController : Controller
	{

		private readonly AppDbContext _db;


		public AsistanController(AppDbContext db)
		{
			_db = db;

		}


		public IActionResult Index()
		{
			IEnumerable<Asistan> objAsistanList = _db.Asistanlar;
			return View(objAsistanList);
		}
		//get
		public IActionResult Create()
		{
			return View();
		}
		//post
		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult Create(Asistan obj)
		{


			_db.Asistanlar.Add(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}

		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var AsistanDb = _db.Asistanlar.Find(id);
			//var  AsistanDbFirst = _db. Asistan.FirstOrDefault(u=>u.Id==id);
			//var  AsistanDbSingle = _db. Asistan.SingleOrDefault(u=>u.Id==id);

			if (AsistanDb == null)
			{
				return NotFound();
			}
			return View(AsistanDb);
		}

		//post
		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult Edit(Asistan obj)
		{


			_db.Asistanlar.Update(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var AsistanDb = _db.Asistanlar.Find(id);
			

			if (AsistanDb == null)
			{
				return NotFound();
			}
			return View(AsistanDb);
		}

		//post
		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult DeletePOST(int? id)
		{
			var obj = _db.Asistanlar.Find(id);
			if (obj == null)
			{
				return NotFound();
			}

			_db.Asistanlar.Remove(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}
	}
}

hastane1/hastane1/Controllers/BolumController.cs
using Microsoft.AspNetCore.Mvc;
using hastane1.Models;
using Microsoft.AspNetCore.Http.HttpResults;


namespace hastane1.Controllers
{
	public class BolumController : Controller
	{

		private readonly AppDbContext _db;


		public BolumController(AppDbContext db)
		{
			_db = db;

		}


		public IActionResult Index()
		{
			IEnumerable<Bolum> objBolumList = _db.Bolumler;
			return View(objBolumList);
		}
		//get
		public IActionResult Create()
		{
			return View();
		}
		//post
		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult Create(Bolum obj)
		{


			_db.Bolumler.Add(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}

		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var BolumDb = _db.Bolumler.Find(id);
			

			if (BolumDb == null)
			{
				return NotFound();
			}
			return View(BolumDb);
		}

		//post
		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult Edit(Bolum obj)
		{


			_db.Bolumler.Update(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var BolumDb = _db.Bolumler.Find(id);
			
			if (BolumDb == null)
			{
				return NotFound();
			}
			return View(BolumDb);
		}

		//post
		[HttpPost]
		[ValidateAntiForgeryToken]

		public IActionResult DeletePOST(int? id)
		{
			var obj = _db.Bolumler.Find(id);
			if (obj == null)
			{
				return NotFound();
			}

			_db.Bolumler.Remove(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}
	}
}

hastane1/hastane1/Controllers/GirisController.cs
using hastane1.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;



namespace hastane1.Controllers
{
    public class GirisController : Controller
    {
        private readonly AppDbContext _context;
        public GirisController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Giris()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Giris(Girisviewmodel model)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.FirstOrDefault(u => u.Username == model.Username);

                if (user != null)
                {
                    if (model.Password == user.Password)
                    {
                        var claims = new List<Claim>
                        {
                           new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                           new Claim(ClaimTypes.Role, user.Role)
                        };
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("Password", "Incorrect password.");
                    }
                }
                else
                {
                    ModelState.AddModelError("Email", "No account found with this email.");
                }
            }

            return View(model);
        }
        public IActionResult Logout()
        {

            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);


            return RedirectToAction("Index", "Home");
        }

    }

}

hastane1/hastane1/Controllers/NobetController.cs
using hastane1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;


public class NobetController : Controller
{
    private readonly AppDbContext _db;

    public NobetController(AppDbContext context)
    {
        _db = context;
    }
  
    public IActionResult Index(int year, int month)
    {
        year = year == 0 ? DateTime.Now.Year : year;
        month = month == 0 ? DateTime.Now.Month : month;

        var nobetler = _db.Nobetler
            .Include(s => s.Asistan)
            .Include(s => s.Bolum)
            .Where(s => s.Tarih.Year == year && s.Tarih.Month == month)
            .ToList();

        ViewBag.Year = year;
        ViewBag.Month = month;
        return View(nobetler);
    }
  

    public IActionResult Create()
    {
        ViewBag.Asistanlar = _db.Asistanlar
            .Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Ad
            }).ToList();
        ViewBag.Bolumler = _db.Bolumler
                    .Select(d => new SelectListItem
                    {
                        Value = d.Id.ToString(),
                        Text = d.BolumAdi
                    }).ToList();
        return View();


    }

    [HttpPost]
    [ValidateAntiForgeryToken]
   
    public IActionResult Create(Nobet Nobet)
    {
        if (ModelState.IsValid)
        {
            
            var existingShift = _db.Nobetler
                .FirstOrDefault(s => s.AsistanId == Nobet.AsistanId && s.Tarih == Nobet.Tarih);

            if (existingShift != null)
            {
                ModelState.AddModelError("", "This assistant already has a shift on the selected date.");
                ViewBag.Asistanlar = _db.Asistanlar
                    .Select(a => new SelectListItem
                    {
                        Value = a.Id.ToString(),
                        Text = a.Ad
                    }).ToList();
                ViewBag.Bolumler = _db.Bolumler
                    .Select(d => new SelectListItem
                    {
                        Value = d.Id.ToString(),
                        Text = d.BolumAdi
                    }).ToList();
                return View(Nobet);
            }

            _db.Nobetler.Add(Nobet);
            _db.SaveChanges();
            TempData["success"] = "Shift added successfully!";
            return RedirectToAction("Index");
        }

        ViewBag.Asistanlar = _db.Asistanlar
                     .Select(a => new SelectListItem
                     {
                         Value = a.Id.ToString(),
                         Text = a.Ad
                     }).ToList();
        ViewBag.Bolumler = _db.Bolumler
            .Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.BolumAdi
            }).ToList();
        return View(Nobet);
    }

    
    [HttpPost]
    [ValidateAntiForgeryToken]
 
    public IActionResult Delete(int id)
    {
        var nobet = _db.Nobetler.Find(id);
        if (nobet == null)
        {
            return NotFound();
        }

        _db.Nobetler.Remove(nobet);
        _db.SaveChanges();
        TempData["success"] = "Shift deleted successfully!";
        return RedirectToAction("Index");
    }


    public IActionResult Detay(int id)
    {
        var nobet = _db.Nobetler
            .Include(s => s.Asistan)
            .Include(s => s.Bolum)
            .FirstOrDefault(s => s.Id == id);

        if (nobet == null)
        {
            return NotFound();
        }

        return View(nobet);
    }
}

hastane1/hastane1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hastane</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/hastane1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.10.2/dist/fullcalendar.min.css" rel="stylesheet">

    <link rel="icon" type="image/x-icon" href="/photos/favicon.ico"> <!-- favicon -->   

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SAKARYA PEDİATRİ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="OgretimUyesi" asp-action="Index">Öğretim Üyesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Asistan" asp-action="Index">Asistan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Bolum" asp-action="Index">Bölüm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Nobet" asp-action="Index">Nöbet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Randevu" asp-action="Index">Randevu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="AcilDurumHaberleri" asp-action="Index">Acil Durum Haberleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Hakkinda" asp-action="Index">Hakkında</a>
                        </li>
                    </ul>
                    <div class="d-flex align-items-center">
                        <a class="btn btn-secondary" asp-controller="Giris" asp-action="Giris">Login</a>
                    </div>
                    <div class="d-flex align-items-center">
                        <a class="btn btn-secondary" asp-controller="Giris" asp-action="Logout">Logout</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="bg-dark text-white text-center py-3 mt-4"
            style="background: linear-gradient(to right, #4f158e, #6a9aee);">
        &copy; 2024  Tıp Fakültesi
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>