hastane1/hastane1/Models/OgretimUyesi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hastane1.Models
{
        public class OgretimUyesi
        {
            [Key]
            public int Id { get; set; }

            [Required]
            [MaxLength(50)]
            public string? Ad { get; set; }

            [Required]
            [MaxLength(50)]
            public string? Soyad { get; set; }

            [MaxLength(15)]
            public string? Telefon { get; set; }

            [Required]
            [EmailAddress]
            public string? Eposta { get; set; }

            public string? Adres { get; set; }

            [ForeignKey("Bolum")]
            public int? SorumluBolumId { get; set; }

            public Bolum? Bolum { get; set; }

            
            [ForeignKey("User")]
            public int? UserId { get; set; }
            public User? User { get; set; }
        

            public ICollection<Randevu>? Randevular { get; set; }
    }

    }

hastane1/hastane1/Controllers/OgretimUyesiController.cs
using Microsoft.AspNetCore.Mvc;
using hastane1.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Authorization;


namespace hastane1.Controllers
{
    public class OgretimUyesiController : Controller
    {

        private readonly AppDbContext _db;


       public OgretimUyesiController(AppDbContext db)
        {
            _db = db;

        }

		

		public IActionResult Index()
        {
            IEnumerable<OgretimUyesi> objOgretimUyesiList = _db.OgretimUyeleri;
            return View(objOgretimUyesiList);
        }
		[Authorize(Roles = "Admin")]
		public IActionResult Create()
		{
			return View();
		}
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public IActionResult Create(OgretimUyesi obj)
        {
         
            
                _db.OgretimUyeleri.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            
          
        }
		[Authorize(Roles = "Admin")]
		public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var OgretimUyesiDb = _db.OgretimUyeleri.Find(id);
         

            if (OgretimUyesiDb == null)
            {
                return NotFound();
            }
            return View(OgretimUyesiDb);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public IActionResult Edit(OgretimUyesi obj)
        {


            _db.OgretimUyeleri.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }
		[Authorize(Roles = "Admin")]
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var OgretimUyesiDb = _db.OgretimUyeleri.Find(id);
		
			if (OgretimUyesiDb == null)
			{
				return NotFound();
			}
			return View(OgretimUyesiDb);
		}

		//post
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public IActionResult DeletePOST(int? id)
		{
			var obj = _db.OgretimUyeleri.Find(id);
			if (obj == null)
			{
				return NotFound();
			}

			_db.OgretimUyeleri.Remove(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");


		}
	}
}

hastane1/hastane1/Views/OgretimUyesi/Create.cshtml
@model	OgretimUyesi

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary"> Ogretım Uyesi Oluştur </h2>
				<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Ad"></label>
			<input asp-for="Ad" class="form-control" />
			<span asp-validation-for="Ad" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Soyad"></label>
			<input asp-for="Soyad" class="form-control" />
			<span asp-validation-for="Soyad" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Telefon"></label>
			<input asp-for="Telefon" class="form-control" />
			<span asp-validation-for="Telefon" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Adres"></label>
			<input asp-for="Adres" class="form-control" />
			<span asp-validation-for="Adres" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Eposta"></label>
			<input asp-for="Eposta" class="form-control" />
			<span asp-validation-for="Eposta" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="SorumluBolumId"></label>
			<input asp-for="SorumluBolumId" class="form-control" />
			<span asp-validation-for="SorumluBolumId" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="UserId"></label>
			<input asp-for="UserId" class="form-control" />
			<span asp-validation-for="UserId" class="text-danger"></span>
		</div>
			
		<button type="submit" class="btn btn-primary" style="width:180px">Oluştur</button>
			<a asp-controller="OgretimUyesi" asp-action="Index" style="width:150px">Listeye  Dön </a>
		

	</div>

</form>

hastane1/hastane1/Views/OgretimUyesi/Delete.cshtml
@model OgretimUyesi

<form method="post" asp-action="DeletePOST">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary"> Ogretım Uyesi Silme </h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Ad"></label>
			<input asp-for="Ad" disabled class="form-control" />

		</div>
		<div class="mb-3">
			<label asp-for="Soyad"></label>
			<input asp-for="Soyad" disabled class="form-control" />

		</div>
		<div class="mb-3">
			<label asp-for="Telefon"></label>
			<input asp-for="Telefon" disabled class="form-control" />

		</div>
		<div class="mb-3">
			<label asp-for="Adres"></label>
			<input asp-for="Adres" disabled class="form-control" />

		</div>
		<div class="mb-3">
			<label asp-for="Eposta"></label>
			<input asp-for="Eposta" disabled class="form-control" />

		</div>
		<div class="mb-3">
			<label asp-for="SorumluBolumId"></label>
			<input asp-for="SorumluBolumId" disabled class="form-control" />

		</div>
		<div class="mb-3">
			<label asp-for="UserId"></label>
			<input asp-for="UserId" disabled class="form-control" />

		</div>

		<button type="submit" class="btn btn-danger" style="width:180px">Sil</button>
		<a asp-controller="OgretimUyesi" asp-action="Index" style="width:150px">Listeye  Dön </a>


	</div>

</form>

hastane1/hastane1/Views/OgretimUyesi/Edit.cshtml
@model	OgretimUyesi

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary"> Ogretım Uyesi Düzenle </h2>
				<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Ad"></label>
			<input asp-for="Ad" class="form-control" />
			<span asp-validation-for="Ad" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Soyad"></label>
			<input asp-for="Soyad" class="form-control" />
			<span asp-validation-for="Soyad" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Telefon"></label>
			<input asp-for="Telefon" class="form-control" />
			<span asp-validation-for="Telefon" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Adres"></label>
			<input asp-for="Adres" class="form-control" />
			<span asp-validation-for="Adres" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Eposta"></label>
			<input asp-for="Eposta" class="form-control" />
			<span asp-validation-for="Eposta" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="SorumluBolumId"></label>
			<input asp-for="SorumluBolumId" class="form-control" />
			<span asp-validation-for="SorumluBolumId" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="UserId"></label>
			<input asp-for="UserId" class="form-control" />
			<span asp-validation-for="UserId" class="text-danger"></span>
		</div>
			
		<button type="submit" class="btn btn-primary" style="width:180px">Düzenle</button>
			<a asp-controller="OgretimUyesi" asp-action="Index" style="width:150px">Listeye  Dön </a>
		

	</div>

</form>

hastane1/hastane1/Views/OgretimUyesi/Index.cshtml
@model IEnumerable<OgretimUyesi>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
	<div class="row pt-4">
	<div class="col-6">
			<h2 class="text-primary"> Ogretım Uyesi Listesi </h2>

	</div>
	@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
	<div class="col-6 text-end">
			<a asp-controller="OgretimUyesi" asp-action="Create" class="btn btn-primary"> 
				<i class="bi bi-plus-circle"></i> &nbsp; YENİ ÖGRETİM ÜYESİ OLUŞTUR
			</a>

	</div>
}
	</div>
	<br /> <br />

<table class="table table-bordered table-striped" style="width:100%"> 
	<thead>
    <tr>
		
		
	<th>

		AD

	</th>
			<th>

				SOYAD

			</th>
			<th>

				TELEFON

			</th>
			<th>

				E POSTA

			</th>
			<th>

				ADRES

			</th>
			<th>

				SORUMLUBÖLGEID

			</th>
			<th>

				USERID

			</th>
			<th></th>
		</tr>

			</thead>
	<tbody>
		@foreach(var obj in Model)
		{
			<tr>
			<td width="50%">
				@obj.Ad
			</td>

				<td width="30%">
					@obj.Soyad
				</td>
				<td width="30%">
					@obj.Telefon
				</td>
				<td width="30%">
					@obj.Eposta
				</td>
				<td width="30%">
					@obj.Adres
				</td>
				<td width="30%">
					@obj.SorumluBolumId
				</td>
				<td width="30%">
					@obj.UserId
				</td>
				<td>
						@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
						
							<div class="w-75 btn-group" role="group">
								<a asp asp-controller="OgretimUyesi" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"> <i class="bi bi-pencil-square"></i>Edit</a>
								<a asp asp-controller="OgretimUyesi" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-primary"> <i class="bi bi-trash-fill"></i>Delete</a>
							</div>
}

					</td>
			</tr>


		}




	</tbody>
</table>
</div>